component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/META-INF/.*
- ./bin/datasets/.*
- ./bin/edu/.*
- ./bin/edu/uci/.*
- ./bin/edu/uci/ics/.*
- ./bin/edu/uci/ics/jung/.*
- ./bin/edu/uci/ics/jung/algorithms/.*
- ./bin/edu/uci/ics/jung/algorithms/blockmodel/.*
- ./bin/edu/uci/ics/jung/algorithms/cluster/.*
- ./bin/edu/uci/ics/jung/algorithms/filters/.*
- ./bin/edu/uci/ics/jung/algorithms/flows/.*
- ./bin/edu/uci/ics/jung/algorithms/generators/.*
- ./bin/edu/uci/ics/jung/algorithms/generators/random/.*
- ./bin/edu/uci/ics/jung/algorithms/importance/.*
- ./bin/edu/uci/ics/jung/algorithms/layout/.*
- ./bin/edu/uci/ics/jung/algorithms/layout/util/.*
- ./bin/edu/uci/ics/jung/algorithms/layout3d/.*
- ./bin/edu/uci/ics/jung/algorithms/matrix/.*
- ./bin/edu/uci/ics/jung/algorithms/metrics/.*
- ./bin/edu/uci/ics/jung/algorithms/scoring/.*
- ./bin/edu/uci/ics/jung/algorithms/scoring/util/.*
- ./bin/edu/uci/ics/jung/algorithms/shortestpath/.*
- ./bin/edu/uci/ics/jung/algorithms/transformation/.*
- ./bin/edu/uci/ics/jung/algorithms/util/.*
- ./bin/edu/uci/ics/jung/graph/.*
- ./bin/edu/uci/ics/jung/graph/event/.*
- ./bin/edu/uci/ics/jung/graph/util/.*
- ./bin/edu/uci/ics/jung/io/.*
- ./bin/edu/uci/ics/jung/io/graphml/.*
- ./bin/edu/uci/ics/jung/io/graphml/parser/.*
- ./bin/edu/uci/ics/jung/samples/.*
- ./bin/edu/uci/ics/jung/visualization/.*
- ./bin/edu/uci/ics/jung/visualization/annotations/.*
- ./bin/edu/uci/ics/jung/visualization/control/.*
- ./bin/edu/uci/ics/jung/visualization/decorators/.*
- ./bin/edu/uci/ics/jung/visualization/jai/.*
- ./bin/edu/uci/ics/jung/visualization/layout/.*
- ./bin/edu/uci/ics/jung/visualization/picking/.*
- ./bin/edu/uci/ics/jung/visualization/renderers/.*
- ./bin/edu/uci/ics/jung/visualization/subLayout/.*
- ./bin/edu/uci/ics/jung/visualization/transform/.*
- ./bin/edu/uci/ics/jung/visualization/transform/shape/.*
- ./bin/edu/uci/ics/jung/visualization/util/.*
- ./bin/edu/uci/ics/jung/visualization3d/.*
- ./bin/edu/uci/ics/jung/visualization3d/control/.*
- ./bin/edu/uci/ics/jung/visualization3d/decorators/.*
- ./bin/edu/uci/ics/jung/visualization3d/layout/.*
- ./bin/images/.*
- ./lib/.*
